package ds

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

type MockedClock struct {
	time int
}

func (m *MockedClock) CurrentMillis() int {
	return m.time
}

func NewMockedClock(time int) *MockedClock {
	return &MockedClock{time: time}
}

func TestAddInANewStream(t *testing.T) {
	streams := NewStreams()
	_, err := streams.Add("Key1", "1526919030473-0", nil)

	assert.NoError(t, err)
}

func TestAddInAExistingStream(t *testing.T) {
	streams := NewStreams()
	_, _ = streams.Add("Key1", "1526919030473-0", nil)
	_, err := streams.Add("Key1", "1526919030473-1", nil)

	assert.NoError(t, err)
}

func TestAddWithSameSequenceAsHeadOfStream(t *testing.T) {
	streams := NewStreams()
	_, _ = streams.Add("Key1", "1526919030473-0", nil)
	_, err := streams.Add("Key1", "1526919030473-0", nil)

	assert.Error(t, err)
}

func TestAddWithHigherTimestampThanHeadOfStream(t *testing.T) {
	streams := NewStreams()
	_, _ = streams.Add("Key1", "1526919030473-10", nil)
	_, err := streams.Add("Key1", "1526919030500-9", nil)

	assert.NoError(t, err)
}

func TestAddWithLowerTimestampThanHeadOfStream(t *testing.T) {
	streams := NewStreams()
	_, _ = streams.Add("Key1", "1526919030473-10", nil)
	_, err := streams.Add("Key1", "1526919030400-9", nil)

	assert.Error(t, err)
}

func TestAddWithZeroZeroKey(t *testing.T) {
	streams := NewStreams()
	_, err := streams.Add("Key1", "0-0", nil)

	assert.Error(t, err)
}

func TestIncludes(t *testing.T) {
	streams := NewStreams()
	contains := streams.Contains("Key1")
	assert.False(t, contains)

	_, _ = streams.Add("Key2", "1526919030400-10", nil)
	contains = streams.Contains("Key1")
	assert.False(t, contains)

	_, _ = streams.Add("Key1", "1526919030400-10", nil)
	contains = streams.Contains("Key1")
	assert.True(t, contains)
}

func TestAddWithAutogenerateSequenceInNonExistingStream(t *testing.T) {
	streams := NewStreams()
	id, err := streams.Add("Key1", "1526919030473-*", nil)

	assert.NoError(t, err)
	assert.Equal(t, "1526919030473-0", id)
}

func TestAddWithAutogenerateSequenceInExistingStream(t *testing.T) {
	streams := NewStreams()
	id, err := streams.Add("Key1", "1526919030473-10", nil)

	assert.NoError(t, err)
	assert.Equal(t, "1526919030473-10", id)

	id, err = streams.Add("Key1", "1526919030473-*", nil)

	assert.NoError(t, err)
	assert.Equal(t, "1526919030473-11", id)
}

func TestAddWithAutogenerateSequenceInExistingStreamWithMultipleTimestampEnteries(t *testing.T) {
	streams := NewStreams()
	id, err := streams.Add("Key1", "1526919030473-10", nil)
	assert.NoError(t, err)
	assert.Equal(t, "1526919030473-10", id)

	id, err = streams.Add("Key1", "1526919030474-10", nil)
	assert.NoError(t, err)
	assert.Equal(t, "1526919030474-10", id)

	id, err = streams.Add("Key1", "1526919030474-*", nil)
	assert.NoError(t, err)
	assert.Equal(t, "1526919030474-11", id)
}

func TestAddWithAutogenerateSequenceWithTimestampZero(t *testing.T) {
	streams := NewStreams()
	id, err := streams.Add("Key1", "0-*", nil)

	assert.NoError(t, err)
	assert.Equal(t, "0-1", id)
}

func TestAddWithFullyAutogeneratedId(t *testing.T) {
	streams := NewStreamsWithClock(NewMockedClock(1526919030474))
	id, err := streams.Add("Key1", "*", nil)

	assert.NoError(t, err)
	assert.Equal(t, "1526919030474-0", id)
}
